# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L_oXRDaK0HlqhhZvuaVQBn7Y_cxxfF8P
"""

from google.colab import drive
drive.mount('/content/drive')

!unzip -q "/content/drive/MyDrive/AI_dataset/archive.zip" -d "/content/dataset"

import torch

from torchvision import datasets
from torchvision.transforms import v2
from torch.utils.data import DataLoader, random_split
import matplotlib.pyplot as plt
from google.colab import drive
import torch.nn as nn
from torchvision import models
# Подготовка трансформаций (MobileNetV2 ждет размер 224x224)
basic_transforms = v2.Compose([
    v2.ToImage(),
    v2.Resize((224, 224), antialias=True),
    v2.ToDtype(torch.float32, scale=True),
    # Стандартная нормализация для моделей ImageNet
    v2.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Путь к папке Images
data_dir = '/content/dataset/images/Images'


full_dataset = datasets.ImageFolder(root=data_dir, transform=basic_transforms)


train_size = int(0.8 * len(full_dataset))
test_size = len(full_dataset) - train_size
train_dataset, test_dataset = random_split(full_dataset, [train_size, test_size])


BATCH_SIZE = 32
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

print(f"Всего классов: {len(full_dataset.classes)}")
print(f"Картинок для обучения: {len(train_dataset)}")



cutmix = v2.CutMix(num_classes=120)


images, labels = next(iter(train_loader))
mixed_images, mixed_labels = cutmix(images, labels)

print("Форма картинок после CutMix:", mixed_images.shape)
print("Форма меток после CutMix:", mixed_labels.shape)

model = models.mobilenet_v2(weights='IMAGENET1K_V1')
print(model.classifier)


NUM_CLASSES = 120


model.classifier[1] = nn.Linear(
    in_features=model.classifier[1].in_features,  # 1280
    out_features=NUM_CLASSES
)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = model.to(device)
print(f"Обучение на: {device}")

# ЭКСПЕРИМЕНТ 1: Дообучение предобученной модели + Adam

criterion = nn.CrossEntropyLoss()

# Оптимизатор Adam
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

from torchvision.transforms import v2

NUM_EPOCHS = 5
cutmix = v2.CutMix(num_classes=NUM_CLASSES)

for epoch in range(NUM_EPOCHS):
    model.train()
    running_loss = 0.0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        # Применяем CutMix к батчу — метки становятся soft (вектор 120 значений)
        images, labels = cutmix(images, labels)

        optimizer.zero_grad()

        outputs = model(images)
        loss = criterion(outputs, labels)  # labels здесь float-тензор [batch, 120]

        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    avg_loss = running_loss / len(train_loader)
    print(f"Epoch [{epoch+1}/{NUM_EPOCHS}] | Loss: {avg_loss:.4f}")

from sklearn.metrics import precision_recall_fscore_support
import numpy as np

model.eval()
all_preds = []
all_targets = []

with torch.no_grad():
    for images, labels in test_loader:  # test_loader — без CutMix
        images = images.to(device)
        outputs = model(images)
        preds = outputs.argmax(dim=1).cpu().numpy()
        all_preds.extend(preds)
        all_targets.extend(labels.numpy())

# Считаем метрики (macro — усредняем по всем 120 классам)
precision, recall, f1, _ = precision_recall_fscore_support(
    all_targets, all_preds, average='macro', zero_division=0
)

print(f"Эксперимент 1 (Предобученная + Adam)")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-Score:  {f1:.4f}")

# ЭКСПЕРИМЕНТ 2: Дообучение предобученной модели + NovoGrad
import torch_optimizer as optim_extra
from torchvision import models
import torch.nn as nn

model2 = models.mobilenet_v2(weights='IMAGENET1K_V1')
model2.classifier[1] = nn.Linear(
    in_features=model2.classifier[1].in_features,
    out_features=NUM_CLASSES
)
model2 = model2.to(device)


optimizer2 = optim_extra.NovoGrad(
    model2.parameters(),
    lr=1e-3,
    betas=(0.95, 0),
    weight_decay=0.001
)

# Цикл обучения
for epoch in range(NUM_EPOCHS):
    model2.train()
    running_loss = 0.0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)
        images, labels = cutmix(images, labels)

        optimizer2.zero_grad()
        outputs = model2(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer2.step()

        running_loss += loss.item()

    print(f"Epoch [{epoch+1}/{NUM_EPOCHS}] | Loss: {running_loss/len(train_loader):.4f}")

model2.eval()
all_preds2 = []
all_targets2 = []

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        outputs = model2(images)
        preds = outputs.argmax(dim=1).cpu().numpy()
        all_preds2.extend(preds)
        all_targets2.extend(labels.numpy())

precision2, recall2, f1_2, _ = precision_recall_fscore_support(
    all_targets2, all_preds2, average='macro', zero_division=0
)

print(f"Эксперимент 2 (Предобученная + NovoGrad)")
print(f"Precision: {precision2:.4f}")
print(f"Recall:    {recall2:.4f}")
print(f"F1-Score:  {f1_2:.4f}")

# ЭКСПЕРИМЕНТ 3: Обучение с нуля + Adam

import torch
import torch.nn as nn
from torchvision import models
from torchvision.transforms import v2
from sklearn.metrics import precision_recall_fscore_support

NUM_CLASSES = 120
NUM_EPOCHS  = 10


model3 = models.mobilenet_v2(weights=None)
model3.classifier[1] = nn.Linear(
    in_features=model3.classifier[1].in_features,   # 1280
    out_features=NUM_CLASSES
)
model3 = model3.to(device)

# Оптимизатор Adam
optimizer3 = torch.optim.Adam(model3.parameters(), lr=1e-3)

# Функция потерь
criterion = nn.CrossEntropyLoss()

# CutMix
cutmix = v2.CutMix(num_classes=NUM_CLASSES)


# Цикл обучения

for epoch in range(NUM_EPOCHS):
    model3.train()
    running_loss = 0.0

    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)


        images, labels = cutmix(images, labels)

        optimizer3.zero_grad()
        outputs = model3(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer3.step()

        running_loss += loss.item()

    avg_loss = running_loss / len(train_loader)
    print(f"Epoch [{epoch+1}/{NUM_EPOCHS}] | Loss: {avg_loss:.4f}")


# Замер метрик на тестовой выборке

model3.eval()
all_preds3   = []
all_targets3 = []

with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        outputs = model3(images)
        preds = outputs.argmax(dim=1).cpu().numpy()
        all_preds3.extend(preds)
        all_targets3.extend(labels.numpy())

precision3, recall3, f1_3, _ = precision_recall_fscore_support(
    all_targets3, all_preds3, average='macro', zero_division=0
)

print(f"\n{'='*45}")
print(f"Эксперимент 3 (С нуля + Adam)")
print(f"Precision : {precision3:.4f}")
print(f"Recall    : {recall3:.4f}")
print(f"F1-Score  : {f1_3:.4f}")