{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "gpuType": "T4",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/RADMIR04KA/PSIAPD/blob/main/untitled3.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "9Ai-jjAFnFi_"
      },
      "outputs": [],
      "source": [
        "from google.colab import drive\n",
        "drive.mount('/content/drive')"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!unzip -q \"/content/drive/MyDrive/AI_dataset/archive.zip\" -d \"/content/dataset\"\n"
      ],
      "metadata": {
        "id": "2G62uCoenlXc"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import os\n",
        "import random\n",
        "from pathlib import Path\n",
        "\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "from PIL import Image\n",
        "\n",
        "import torch\n",
        "import torch.nn as nn\n",
        "import torch.optim as optim\n",
        "from torch.utils.data import Dataset, DataLoader\n",
        "\n",
        "from torchvision.transforms import v2\n",
        "\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.metrics import precision_score, recall_score, f1_score\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# 1. БАЗОВЫЕ НАСТРОЙКИ\n",
        "# =========================================================\n",
        "\n",
        "DEVICE = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
        "SEED = 42\n",
        "\n",
        "# Укажи путь к папке Images из Stanford Dogs Dataset\n",
        "# Пример структуры:\n",
        "# /content/Images/n02085620-Chihuahua/xxx.jpg\n",
        "DATA_DIR = Path(\"/content/dataset/images/Images\")\n",
        "\n",
        "IMG_SIZE = 224\n",
        "BATCH_SIZE = 32\n",
        "EPOCHS = 15\n",
        "LEARNING_RATE = 1e-3\n",
        "BEST_MODEL_PATH = \"/content/best_mobilenetv2_custom_scratch.pth\"\n",
        "\n",
        "\n",
        "def set_seed(seed=42):\n",
        "    random.seed(seed)\n",
        "    np.random.seed(seed)\n",
        "    torch.manual_seed(seed)\n",
        "    torch.cuda.manual_seed_all(seed)\n",
        "\n",
        "\n",
        "set_seed(SEED)\n",
        "print(\"Device:\", DEVICE)\n",
        "\n",
        "assert DATA_DIR.exists(), f\"Папка {DATA_DIR} не найдена\"\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# 2. ПОДГОТОВКА ДАННЫХ\n",
        "# =========================================================\n",
        "\n",
        "classes = sorted([d.name for d in DATA_DIR.iterdir() if d.is_dir()])\n",
        "class_to_idx = {cls_name: idx for idx, cls_name in enumerate(classes)}\n",
        "idx_to_class = {idx: cls_name for cls_name, idx in class_to_idx.items()}\n",
        "num_classes = len(classes)\n",
        "\n",
        "print(\"Количество классов:\", num_classes)\n",
        "\n",
        "image_paths = []\n",
        "labels = []\n",
        "\n",
        "for cls_name in classes:\n",
        "    class_dir = DATA_DIR / cls_name\n",
        "    for img_path in class_dir.glob(\"*\"):\n",
        "        if img_path.suffix.lower() in [\".jpg\", \".jpeg\", \".png\"]:\n",
        "            image_paths.append(str(img_path))\n",
        "            labels.append(class_to_idx[cls_name])\n",
        "\n",
        "image_paths = np.array(image_paths)\n",
        "labels = np.array(labels)\n",
        "\n",
        "print(\"Количество изображений:\", len(image_paths))\n",
        "\n",
        "train_paths, temp_paths, train_labels, temp_labels = train_test_split(\n",
        "    image_paths,\n",
        "    labels,\n",
        "    test_size=0.30,\n",
        "    stratify=labels,\n",
        "    random_state=SEED\n",
        ")\n",
        "\n",
        "val_paths, test_paths, val_labels, test_labels = train_test_split(\n",
        "    temp_paths,\n",
        "    temp_labels,\n",
        "    test_size=0.50,\n",
        "    stratify=temp_labels,\n",
        "    random_state=SEED\n",
        ")\n",
        "\n",
        "print(\"Train:\", len(train_paths))\n",
        "print(\"Val:\", len(val_paths))\n",
        "print(\"Test:\", len(test_paths))\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# 3. DATASET И ТРАНСФОРМАЦИИ\n",
        "# =========================================================\n",
        "\n",
        "class StanfordDogsDataset(Dataset):\n",
        "    def __init__(self, image_paths, labels, transform=None):\n",
        "        self.image_paths = list(image_paths)\n",
        "        self.labels = list(labels)\n",
        "        self.transform = transform\n",
        "\n",
        "    def __len__(self):\n",
        "        return len(self.image_paths)\n",
        "\n",
        "    def __getitem__(self, idx):\n",
        "        image = Image.open(self.image_paths[idx]).convert(\"RGB\")\n",
        "        label = self.labels[idx]\n",
        "\n",
        "        if self.transform is not None:\n",
        "            image = self.transform(image)\n",
        "\n",
        "        return image, label\n",
        "\n",
        "\n",
        "train_transform = v2.Compose([\n",
        "    v2.Resize((IMG_SIZE, IMG_SIZE)),\n",
        "    v2.RandomHorizontalFlip(p=0.5),\n",
        "    v2.RandomRotation(degrees=15),\n",
        "    v2.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.05),\n",
        "    v2.ToImage(),\n",
        "    v2.ToDtype(torch.float32, scale=True),\n",
        "    v2.Normalize(mean=[0.485, 0.456, 0.406],\n",
        "                 std=[0.229, 0.224, 0.225]),\n",
        "])\n",
        "\n",
        "eval_transform = v2.Compose([\n",
        "    v2.Resize((IMG_SIZE, IMG_SIZE)),\n",
        "    v2.ToImage(),\n",
        "    v2.ToDtype(torch.float32, scale=True),\n",
        "    v2.Normalize(mean=[0.485, 0.456, 0.406],\n",
        "                 std=[0.229, 0.224, 0.225]),\n",
        "])\n",
        "\n",
        "train_dataset = StanfordDogsDataset(train_paths, train_labels, transform=train_transform)\n",
        "val_dataset = StanfordDogsDataset(val_paths, val_labels, transform=eval_transform)\n",
        "test_dataset = StanfordDogsDataset(test_paths, test_labels, transform=eval_transform)\n",
        "\n",
        "train_loader = DataLoader(\n",
        "    train_dataset,\n",
        "    batch_size=BATCH_SIZE,\n",
        "    shuffle=True,\n",
        "    num_workers=2,\n",
        "    pin_memory=True\n",
        ")\n",
        "\n",
        "val_loader = DataLoader(\n",
        "    val_dataset,\n",
        "    batch_size=BATCH_SIZE,\n",
        "    shuffle=False,\n",
        "    num_workers=2,\n",
        "    pin_memory=True\n",
        ")\n",
        "\n",
        "test_loader = DataLoader(\n",
        "    test_dataset,\n",
        "    batch_size=BATCH_SIZE,\n",
        "    shuffle=False,\n",
        "    num_workers=2,\n",
        "    pin_memory=True\n",
        ")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# 4. РУЧНАЯ РЕАЛИЗАЦИЯ MOBILE NET V2\n",
        "# =========================================================\n",
        "\n",
        "class ConvBNReLU(nn.Sequential):\n",
        "    \"\"\"\n",
        "    Базовый блок:\n",
        "    Conv2d -> BatchNorm2d -> ReLU6\n",
        "\n",
        "    ReLU6 используется в MobileNetV2.\n",
        "    \"\"\"\n",
        "    def __init__(self, in_channels, out_channels, kernel_size=3, stride=1, groups=1):\n",
        "        padding = (kernel_size - 1) // 2\n",
        "        super().__init__(\n",
        "            nn.Conv2d(\n",
        "                in_channels=in_channels,\n",
        "                out_channels=out_channels,\n",
        "                kernel_size=kernel_size,\n",
        "                stride=stride,\n",
        "                padding=padding,\n",
        "                groups=groups,\n",
        "                bias=False\n",
        "            ),\n",
        "            nn.BatchNorm2d(out_channels),\n",
        "            nn.ReLU6(inplace=True)\n",
        "        )\n",
        "\n",
        "\n",
        "class InvertedResidual(nn.Module):\n",
        "    \"\"\"\n",
        "    Главный блок MobileNetV2:\n",
        "\n",
        "    1) 1x1 expansion conv: расширяет число каналов\n",
        "    2) 3x3 depthwise conv: отдельная свертка по каждому каналу\n",
        "    3) 1x1 projection conv: сжимает каналы к выходной размерности\n",
        "\n",
        "    Если stride=1 и число входных/выходных каналов одинаково,\n",
        "    используется residual connection.\n",
        "    \"\"\"\n",
        "    def __init__(self, in_channels, out_channels, stride, expand_ratio):\n",
        "        super().__init__()\n",
        "        assert stride in [1, 2]\n",
        "\n",
        "        hidden_dim = int(round(in_channels * expand_ratio))\n",
        "        self.use_res_connect = (stride == 1 and in_channels == out_channels)\n",
        "\n",
        "        layers = []\n",
        "\n",
        "        # 1. Expansion layer\n",
        "        if expand_ratio != 1:\n",
        "            layers.append(\n",
        "                ConvBNReLU(\n",
        "                    in_channels=in_channels,\n",
        "                    out_channels=hidden_dim,\n",
        "                    kernel_size=1,\n",
        "                    stride=1\n",
        "                )\n",
        "            )\n",
        "\n",
        "        # 2. Depthwise convolution\n",
        "        layers.append(\n",
        "            ConvBNReLU(\n",
        "                in_channels=hidden_dim,\n",
        "                out_channels=hidden_dim,\n",
        "                kernel_size=3,\n",
        "                stride=stride,\n",
        "                groups=hidden_dim\n",
        "            )\n",
        "        )\n",
        "\n",
        "        # 3. Projection layer\n",
        "        layers.append(\n",
        "            nn.Conv2d(\n",
        "                in_channels=hidden_dim,\n",
        "                out_channels=out_channels,\n",
        "                kernel_size=1,\n",
        "                stride=1,\n",
        "                padding=0,\n",
        "                bias=False\n",
        "            )\n",
        "        )\n",
        "        layers.append(nn.BatchNorm2d(out_channels))\n",
        "\n",
        "        self.block = nn.Sequential(*layers)\n",
        "\n",
        "    def forward(self, x):\n",
        "        if self.use_res_connect:\n",
        "            return x + self.block(x)\n",
        "        return self.block(x)\n",
        "\n",
        "\n",
        "class MobileNetV2Custom(nn.Module):\n",
        "    \"\"\"\n",
        "    Полностью ручная реализация MobileNetV2.\n",
        "\n",
        "    Архитектура:\n",
        "    1. Начальный Conv-BN-ReLU6\n",
        "    2. Серии Inverted Residual блоков\n",
        "    3. Финальный 1x1 Conv-BN-ReLU6\n",
        "    4. Global Average Pooling\n",
        "    5. Dropout + Linear classifier\n",
        "\n",
        "    Конфигурация блоков:\n",
        "    [expand_ratio, out_channels, num_blocks, stride]\n",
        "    \"\"\"\n",
        "    def __init__(self, num_classes=120, width_mult=1.0, dropout=0.2):\n",
        "        super().__init__()\n",
        "\n",
        "        input_channel = 32\n",
        "        last_channel = 1280\n",
        "\n",
        "        inverted_residual_setting = [\n",
        "            [1,  16, 1, 1],\n",
        "            [6,  24, 2, 2],\n",
        "            [6,  32, 3, 2],\n",
        "            [6,  64, 4, 2],\n",
        "            [6,  96, 3, 1],\n",
        "            [6, 160, 3, 2],\n",
        "            [6, 320, 1, 1],\n",
        "        ]\n",
        "\n",
        "        input_channel = int(input_channel * width_mult)\n",
        "        self.last_channel = int(last_channel * max(1.0, width_mult))\n",
        "\n",
        "        features = []\n",
        "\n",
        "        # Начальный слой\n",
        "        features.append(\n",
        "            ConvBNReLU(\n",
        "                in_channels=3,\n",
        "                out_channels=input_channel,\n",
        "                kernel_size=3,\n",
        "                stride=2\n",
        "            )\n",
        "        )\n",
        "\n",
        "        # Основные inverted residual блоки\n",
        "        for t, c, n, s in inverted_residual_setting:\n",
        "            output_channel = int(c * width_mult)\n",
        "\n",
        "            for i in range(n):\n",
        "                stride = s if i == 0 else 1\n",
        "                features.append(\n",
        "                    InvertedResidual(\n",
        "                        in_channels=input_channel,\n",
        "                        out_channels=output_channel,\n",
        "                        stride=stride,\n",
        "                        expand_ratio=t\n",
        "                    )\n",
        "                )\n",
        "                input_channel = output_channel\n",
        "\n",
        "        # Финальный 1x1 conv\n",
        "        features.append(\n",
        "            ConvBNReLU(\n",
        "                in_channels=input_channel,\n",
        "                out_channels=self.last_channel,\n",
        "                kernel_size=1,\n",
        "                stride=1\n",
        "            )\n",
        "        )\n",
        "\n",
        "        self.features = nn.Sequential(*features)\n",
        "        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))\n",
        "        self.classifier = nn.Sequential(\n",
        "            nn.Dropout(p=dropout),\n",
        "            nn.Linear(self.last_channel, num_classes)\n",
        "        )\n",
        "\n",
        "        self._initialize_weights()\n",
        "\n",
        "    def forward(self, x):\n",
        "        x = self.features(x)\n",
        "        x = self.avgpool(x)\n",
        "        x = torch.flatten(x, 1)\n",
        "        x = self.classifier(x)\n",
        "        return x\n",
        "\n",
        "    def _initialize_weights(self):\n",
        "        \"\"\"\n",
        "        Инициализация весов с нуля:\n",
        "        - Conv2d: Kaiming Normal\n",
        "        - BatchNorm2d: weight=1, bias=0\n",
        "        - Linear: normal(0, 0.01)\n",
        "        \"\"\"\n",
        "        for m in self.modules():\n",
        "            if isinstance(m, nn.Conv2d):\n",
        "                nn.init.kaiming_normal_(m.weight, mode=\"fan_out\")\n",
        "                if m.bias is not None:\n",
        "                    nn.init.zeros_(m.bias)\n",
        "\n",
        "            elif isinstance(m, nn.BatchNorm2d):\n",
        "                nn.init.ones_(m.weight)\n",
        "                nn.init.zeros_(m.bias)\n",
        "\n",
        "            elif isinstance(m, nn.Linear):\n",
        "                nn.init.normal_(m.weight, 0, 0.01)\n",
        "                nn.init.zeros_(m.bias)\n",
        "\n",
        "\n",
        "model = MobileNetV2Custom(num_classes=num_classes, width_mult=1.0, dropout=0.2).to(DEVICE)\n",
        "\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# 5. LOSS И OPTIMIZER\n",
        "# =========================================================\n",
        "\n",
        "criterion = nn.CrossEntropyLoss()\n",
        "optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# 6. ФУНКЦИИ ОБУЧЕНИЯ И ОЦЕНКИ\n",
        "# =========================================================\n",
        "\n",
        "def train_one_epoch(model, loader, criterion, optimizer, device):\n",
        "    model.train()\n",
        "\n",
        "    running_loss = 0.0\n",
        "    correct = 0\n",
        "    total = 0\n",
        "\n",
        "    for images, labels in loader:\n",
        "        images = images.to(device, non_blocking=True)\n",
        "        labels = labels.to(device, non_blocking=True)\n",
        "\n",
        "        optimizer.zero_grad()\n",
        "\n",
        "        outputs = model(images)\n",
        "        loss = criterion(outputs, labels)\n",
        "\n",
        "        loss.backward()\n",
        "        optimizer.step()\n",
        "\n",
        "        running_loss += loss.item() * images.size(0)\n",
        "\n",
        "        preds = torch.argmax(outputs, dim=1)\n",
        "        correct += (preds == labels).sum().item()\n",
        "        total += labels.size(0)\n",
        "\n",
        "    epoch_loss = running_loss / len(loader.dataset)\n",
        "    epoch_acc = correct / total\n",
        "    return epoch_loss, epoch_acc\n",
        "\n",
        "\n",
        "@torch.no_grad()\n",
        "def evaluate(model, loader, criterion, device):\n",
        "    model.eval()\n",
        "\n",
        "    running_loss = 0.0\n",
        "    correct = 0\n",
        "    total = 0\n",
        "\n",
        "    all_preds = []\n",
        "    all_targets = []\n",
        "\n",
        "    for images, labels in loader:\n",
        "        images = images.to(device, non_blocking=True)\n",
        "        labels = labels.to(device, non_blocking=True)\n",
        "\n",
        "        outputs = model(images)\n",
        "        loss = criterion(outputs, labels)\n",
        "\n",
        "        running_loss += loss.item() * images.size(0)\n",
        "\n",
        "        preds = torch.argmax(outputs, dim=1)\n",
        "        correct += (preds == labels).sum().item()\n",
        "        total += labels.size(0)\n",
        "\n",
        "        all_preds.extend(preds.cpu().numpy())\n",
        "        all_targets.extend(labels.cpu().numpy())\n",
        "\n",
        "    epoch_loss = running_loss / len(loader.dataset)\n",
        "    epoch_acc = correct / total\n",
        "\n",
        "    return epoch_loss, epoch_acc, np.array(all_targets), np.array(all_preds)\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# 7. ОБУЧЕНИЕ\n",
        "# =========================================================\n",
        "\n",
        "best_val_loss = float(\"inf\")\n",
        "\n",
        "history = {\n",
        "    \"train_loss\": [],\n",
        "    \"train_acc\": [],\n",
        "    \"val_loss\": [],\n",
        "    \"val_acc\": []\n",
        "}\n",
        "\n",
        "for epoch in range(EPOCHS):\n",
        "    train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer, DEVICE)\n",
        "    val_loss, val_acc, _, _ = evaluate(model, val_loader, criterion, DEVICE)\n",
        "\n",
        "    history[\"train_loss\"].append(train_loss)\n",
        "    history[\"train_acc\"].append(train_acc)\n",
        "    history[\"val_loss\"].append(val_loss)\n",
        "    history[\"val_acc\"].append(val_acc)\n",
        "\n",
        "    if val_loss < best_val_loss:\n",
        "        best_val_loss = val_loss\n",
        "        torch.save(model.state_dict(), BEST_MODEL_PATH)\n",
        "\n",
        "    print(\n",
        "        f\"Epoch [{epoch + 1}/{EPOCHS}] | \"\n",
        "        f\"train_loss={train_loss:.4f} | train_acc={train_acc:.4f} | \"\n",
        "        f\"val_loss={val_loss:.4f} | val_acc={val_acc:.4f}\"\n",
        "    )\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# 8. ЗАГРУЗКА ЛУЧШЕЙ МОДЕЛИ\n",
        "# =========================================================\n",
        "\n",
        "model.load_state_dict(torch.load(BEST_MODEL_PATH, map_location=DEVICE))\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# 9. ОЦЕНКА НА TEST: PRECISION / RECALL / F1-SCORE\n",
        "# =========================================================\n",
        "\n",
        "test_loss, test_acc, y_true, y_pred = evaluate(model, test_loader, criterion, DEVICE)\n",
        "\n",
        "precision = precision_score(y_true, y_pred, average=\"macro\", zero_division=0)\n",
        "recall = recall_score(y_true, y_pred, average=\"macro\", zero_division=0)\n",
        "f1 = f1_score(y_true, y_pred, average=\"macro\", zero_division=0)\n",
        "\n",
        "print(\"\\nРезультаты на тестовой выборке:\")\n",
        "print(f\"Test Loss:  {test_loss:.4f}\")\n",
        "print(f\"Test Acc:   {test_acc:.4f}\")\n",
        "print(f\"Precision:  {precision:.4f}\")\n",
        "print(f\"Recall:     {recall:.4f}\")\n",
        "print(f\"F1-score:   {f1:.4f}\")\n",
        "\n",
        "\n",
        "# =========================================================\n",
        "# 10. ИТОГОВАЯ ТАБЛИЦА\n",
        "# =========================================================\n",
        "\n",
        "results_df = pd.DataFrame([\n",
        "    {\n",
        "        \"Model\": \"MobileNetV2 custom from scratch + Adam\",\n",
        "        \"Test Loss\": test_loss,\n",
        "        \"Test Accuracy\": test_acc,\n",
        "        \"Precision\": precision,\n",
        "        \"Recall\": recall,\n",
        "        \"F1-score\": f1\n",
        "    }\n",
        "])\n",
        "\n",
        "print(\"\\nИтоговая таблица:\")\n",
        "print(results_df)"
      ],
      "metadata": {
        "id": "KW8oQHjw4dam",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "45d77169-bff8-406d-b270-4a1efd89461e"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Device: cuda\n",
            "Количество классов: 120\n",
            "Количество изображений: 20580\n",
            "Train: 14406\n",
            "Val: 3087\n",
            "Test: 3087\n",
            "Epoch [1/15] | train_loss=4.7521 | train_acc=0.0182 | val_loss=4.6240 | val_acc=0.0198\n",
            "Epoch [2/15] | train_loss=4.4480 | train_acc=0.0312 | val_loss=4.3301 | val_acc=0.0434\n",
            "Epoch [3/15] | train_loss=4.3073 | train_acc=0.0446 | val_loss=4.3257 | val_acc=0.0437\n",
            "Epoch [4/15] | train_loss=4.1641 | train_acc=0.0532 | val_loss=4.0782 | val_acc=0.0658\n",
            "Epoch [5/15] | train_loss=4.0259 | train_acc=0.0682 | val_loss=4.0272 | val_acc=0.0661\n",
            "Epoch [6/15] | train_loss=3.9016 | train_acc=0.0842 | val_loss=3.9281 | val_acc=0.0732\n",
            "Epoch [7/15] | train_loss=3.7929 | train_acc=0.0985 | val_loss=3.9187 | val_acc=0.0943\n",
            "Epoch [8/15] | train_loss=3.6780 | train_acc=0.1110 | val_loss=3.6417 | val_acc=0.1150\n",
            "Epoch [9/15] | train_loss=3.5290 | train_acc=0.1350 | val_loss=3.5483 | val_acc=0.1490\n",
            "Epoch [10/15] | train_loss=3.3951 | train_acc=0.1567 | val_loss=3.5771 | val_acc=0.1448\n",
            "Epoch [11/15] | train_loss=3.2719 | train_acc=0.1794 | val_loss=3.2203 | val_acc=0.1814\n",
            "Epoch [12/15] | train_loss=3.1163 | train_acc=0.2095 | val_loss=3.2854 | val_acc=0.1775\n",
            "Epoch [13/15] | train_loss=2.9931 | train_acc=0.2316 | val_loss=2.9883 | val_acc=0.2271\n",
            "Epoch [14/15] | train_loss=2.8508 | train_acc=0.2606 | val_loss=2.8082 | val_acc=0.2604\n",
            "Epoch [15/15] | train_loss=2.7181 | train_acc=0.2831 | val_loss=2.8128 | val_acc=0.2653\n",
            "\n",
            "Результаты на тестовой выборке:\n",
            "Test Loss:  2.8183\n",
            "Test Acc:   0.2731\n",
            "Precision:  0.2774\n",
            "Recall:     0.2707\n",
            "F1-score:   0.2452\n",
            "\n",
            "Итоговая таблица:\n",
            "                                    Model  Test Loss  Test Accuracy  \\\n",
            "0  MobileNetV2 custom from scratch + Adam   2.818294       0.273081   \n",
            "\n",
            "   Precision    Recall  F1-score  \n",
            "0   0.277378  0.270657  0.245224  \n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "test_loss, test_acc, y_true, y_pred = evaluate(model, test_loader, criterion, device)\n",
        "\n",
        "# Основные метрики классификации\n",
        "precision = precision_score(y_true, y_pred, average=\"macro\", zero_division=0)\n",
        "recall = recall_score(y_true, y_pred, average=\"macro\", zero_division=0)\n",
        "f1 = f1_score(y_true, y_pred, average=\"macro\", zero_division=0)\n",
        "\n",
        "print(\"Результаты на тестовой выборке:\")\n",
        "print(f\"Test Loss:  {test_loss:.4f}\")\n",
        "print(f\"Test Acc:   {test_acc:.4f}\")\n",
        "print(f\"Precision:  {precision:.4f}\")\n",
        "print(f\"Recall:     {recall:.4f}\")\n",
        "print(f\"F1-score:   {f1:.4f}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "yVU6788Z0gl_",
        "outputId": "a7f02417-d5a3-4e16-87ea-9aeb31f9d3bd"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Результаты на тестовой выборке:\n",
            "Test Loss:  2.7512\n",
            "Test Acc:   0.2776\n",
            "Precision:  0.2903\n",
            "Recall:     0.2697\n",
            "F1-score:   0.2507\n"
          ]
        }
      ]
    }
  ]
}