# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BOmSJrZ4X4aTHWSBR3avRdYdo-Iul3Uz
"""

!rm -f /content/howto100m_project/metadata/HowTo100M.zip

# ============================================================
# CELL 1: IMPORTS + HOWTO100M METADATA + VIDEO SUBSET DOWNLOAD
# ============================================================

# -------------------------
# Install dependencies
# -------------------------
!pip install -q transformers scikit-learn tqdm matplotlib seaborn opencv-python yt-dlp joblib pandas

# -------------------------
# Imports
# -------------------------
import os
import gc
import csv
import random
import subprocess
from pathlib import Path
from collections import defaultdict

import numpy as np
import pandas as pd
import torch

from tqdm import tqdm

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# -------------------------
# Reproducibility
# -------------------------
random.seed(42)
np.random.seed(42)
torch.manual_seed(42)

# -------------------------
# Project settings
# -------------------------
BASE_DIR = Path("/content/howto100m_project")
META_DIR = BASE_DIR / "metadata"
VIDEO_DIR = BASE_DIR / "videos"

BASE_DIR.mkdir(parents=True, exist_ok=True)
META_DIR.mkdir(parents=True, exist_ok=True)
VIDEO_DIR.mkdir(parents=True, exist_ok=True)

print("Base directory:", BASE_DIR)
print("Metadata directory:", META_DIR)
print("Videos directory:", VIDEO_DIR)

# -------------------------
# Small Colab-friendly settings
# -------------------------
# Максимальное количество 100
MAX_CLASSES = 5
SAMPLES_PER_CLASS = 20
MAX_METADATA_ROWS_TO_SCAN = 100000

print("MAX_CLASSES:", MAX_CLASSES)
print("SAMPLES_PER_CLASS:", SAMPLES_PER_CLASS)
print("MAX_METADATA_ROWS_TO_SCAN:", MAX_METADATA_ROWS_TO_SCAN)

# -------------------------
# Download HowTo100M metadata archive
# -------------------------

os.chdir(META_DIR)

if not (META_DIR / "HowTo100M.zip").exists():
    print("Downloading HowTo100M metadata archive...")
    !wget -q --show-progress -O HowTo100M.zip https://www.rocq.inria.fr/cluster-willow/amiech/howto100m/HowTo100M.zip
else:
    print("HowTo100M.zip already exists.")

# -------------------------
# Unzip only needed files
# -------------------------

print("Extracting metadata files...")

!unzip -o -j HowTo100M.zip "HowTo100M_v1.csv" -d .
!unzip -o -j HowTo100M.zip "task_ids.csv" -d .

CSV_PATH = META_DIR / "HowTo100M_v1.csv"
TASK_IDS_PATH = META_DIR / "task_ids.csv"

if not CSV_PATH.exists():
    raise RuntimeError("HowTo100M_v1.csv was not extracted.")

if not TASK_IDS_PATH.exists():
    raise RuntimeError("task_ids.csv was not extracted.")

print("Metadata files ready:")
print("-", CSV_PATH)
print("-", TASK_IDS_PATH)

# -------------------------
# Load task id -> task description
# -------------------------
task_id_to_description = {}

with open(TASK_IDS_PATH, "r", encoding="utf-8") as f:
    reader = csv.reader(f, delimiter="\t")
    for row in reader:
        if len(row) >= 2:
            task_id = str(row[0])
            task_desc = str(row[1])
            task_id_to_description[task_id] = task_desc

print("Loaded task descriptions:", len(task_id_to_description))

# -------------------------
# Health-like keywords
# -------------------------
health_keywords = [
    "exercise", "workout", "yoga", "fitness",
    "massage", "meditation", "stretch",
    "training", "therapy", "rehab",
    "health", "body", "muscle", "gym",
    "pilates", "cardio", "warm up", "warm-up"
]

def is_health_text(text):
    text = str(text).lower()
    return any(keyword in text for keyword in health_keywords)

def make_label(text):
    text = str(text).lower()

    if "yoga" in text:
        return "yoga"
    elif "workout" in text or "fitness" in text or "gym" in text or "exercise" in text:
        return "fitness"
    elif "massage" in text:
        return "massage"
    elif "meditation" in text:
        return "meditation"
    elif "stretch" in text or "warm up" in text or "warm-up" in text:
        return "stretch"
    else:
        return "therapy"

# -------------------------
# Read HowTo100M metadata without loading everything into RAM
# -------------------------
# CSV columns according to HowTo100M:
# video_id, category_1, category_2, rank, task_id
print("Scanning HowTo100M_v1.csv for health-like subset...")

records_by_label = defaultdict(list)

with open(CSV_PATH, "r", encoding="utf-8") as f:
    reader = csv.DictReader(f)

    for row_idx, row in enumerate(reader):
        if row_idx >= MAX_METADATA_ROWS_TO_SCAN:
            break

        video_id = str(row.get("video_id", "")).strip()
        category_1 = str(row.get("category_1", "")).strip()
        category_2 = str(row.get("category_2", "")).strip()
        task_id = str(row.get("task_id", "")).strip()
        rank = str(row.get("rank", "")).strip()

        task_description = task_id_to_description.get(task_id, "")

        combined_text = " ".join([
            category_1,
            category_2,
            task_description
        ])

        if not video_id:
            continue

        if not is_health_text(combined_text):
            continue

        label = make_label(combined_text)

        if len(records_by_label[label]) < SAMPLES_PER_CLASS:
            records_by_label[label].append({
                "video_id": video_id,
                "youtube_url": f"https://www.youtube.com/watch?v={video_id}",
                "category_1": category_1,
                "category_2": category_2,
                "task_id": task_id,
                "task_description": task_description,
                "rank": rank,
                "label": label
            })

        ready_labels = [
            label_name
            for label_name, items in records_by_label.items()
            if len(items) >= SAMPLES_PER_CLASS
        ]

        if len(ready_labels) >= MAX_CLASSES:
            break

# -------------------------
# Build selected metadata subset
# -------------------------
selected_labels = sorted([
    label_name
    for label_name, items in records_by_label.items()
    if len(items) > 0
])[:MAX_CLASSES]

selected_records = []

for label_name in selected_labels:
    selected_records.extend(records_by_label[label_name][:SAMPLES_PER_CLASS])

random.shuffle(selected_records)

print("Selected labels:", selected_labels)
print("Selected metadata records:", len(selected_records))

if len(selected_records) == 0:
    raise RuntimeError(
        "No health-like records found. Increase MAX_METADATA_ROWS_TO_SCAN."
    )

print("\nExample selected records:")
for item in selected_records[:5]:
    print(item)

# -------------------------
# Download videos with yt-dlp
# -------------------------

def download_youtube_video(youtube_url, output_path):
    output_path = str(output_path)

    if os.path.exists(output_path) and os.path.getsize(output_path) > 50_000:
        return True

    command = [
        "yt-dlp",
        "--quiet",
        "--no-warnings",
        "-f",
        "mp4[height<=360]/best[height<=360]/best",
        "--merge-output-format",
        "mp4",
        "-o",
        output_path,
        youtube_url
    ]

    result = subprocess.run(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )

    return os.path.exists(output_path) and os.path.getsize(output_path) > 50_000

print("\nDownloading available YouTube videos...")

downloaded_records = []

for idx, item in enumerate(tqdm(selected_records)):
    video_id = item["video_id"]
    youtube_url = item["youtube_url"]

    output_path = VIDEO_DIR / f"{video_id}.mp4"

    ok = download_youtube_video(youtube_url, output_path)

    if ok:
        new_item = dict(item)
        new_item["video_path"] = str(output_path)
        downloaded_records.append(new_item)

print("Downloaded videos:", len(downloaded_records))

if len(downloaded_records) < 8:
    print(
        "WARNING: Very few videos were downloaded. "
        "Increase MAX_METADATA_ROWS_TO_SCAN, MAX_CLASSES, or SAMPLES_PER_CLASS."
    )

# -------------------------
# Encode labels
# -------------------------
downloaded_label_names = [item["label"] for item in downloaded_records]

le_subset = LabelEncoder()
downloaded_label_ids = le_subset.fit_transform(downloaded_label_names)

for i in range(len(downloaded_records)):
    downloaded_records[i]["label_id"] = int(downloaded_label_ids[i])

print("Final classes:", le_subset.classes_)
print("Final downloaded records:", len(downloaded_records))

print("\nDownloaded examples:")
for item in downloaded_records[:5]:
    print(item["video_path"], "->", item["label"])

# ============================================================
# CELL 2: VIDEOMAE FEATURE EXTRACTION + TRAINING
# ============================================================

import gc
import cv2
import numpy as np
import torch

from tqdm import tqdm
from transformers import AutoImageProcessor, VideoMAEModel
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# -------------------------
# Device
# -------------------------
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# -------------------------
# Load VideoMAE
# -------------------------
MODEL_NAME = "MCG-NJU/videomae-base"

processor = AutoImageProcessor.from_pretrained(MODEL_NAME, use_fast=False)
videomae = VideoMAEModel.from_pretrained(MODEL_NAME).to(device)

videomae.eval()

print("VideoMAE loaded successfully.")

# -------------------------
# Extract frames from video file
# -------------------------
def extract_frames(video_path, num_frames=16, target_size=160):
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        raise ValueError("Could not open video.")

    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if total_frames <= 0:
        cap.release()
        raise ValueError("Video has zero frames.")

    frame_indices = np.linspace(0, total_frames - 1, num_frames).astype(int)
    needed = set(frame_indices.tolist())

    frames = []
    current_index = 0

    while True:
        ret, frame = cap.read()

        if not ret:
            break

        if current_index in needed:
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            frame = cv2.resize(frame, (target_size, target_size))
            frames.append(frame)

        current_index += 1

        if len(frames) >= num_frames:
            break

    cap.release()

    if len(frames) == 0:
        raise ValueError("No frames extracted.")

    while len(frames) < num_frames:
        frames.append(frames[-1])

    frames = np.array(frames, dtype=np.uint8)

    return frames

# -------------------------
# VideoMAE features
# -------------------------
def get_videomae_features(video_path):
    frames = extract_frames(
        video_path=video_path,
        num_frames=16,
        target_size=160
    )

    inputs = processor(
        list(frames),
        return_tensors="pt"
    )

    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    with torch.no_grad():
        outputs = videomae(**inputs)

    features = outputs.last_hidden_state.mean(dim=1).squeeze(0).cpu().numpy()

    del frames
    del inputs
    del outputs

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    gc.collect()

    return features.astype(np.float32)

# -------------------------
# Extract features
# -------------------------
X = []
y = []
used_records = []

print("Extracting VideoMAE features...")

for item in tqdm(downloaded_records):
    try:
        video_path = item["video_path"]
        label_id = item["label_id"]

        feature_vector = get_videomae_features(video_path)

        X.append(feature_vector)
        y.append(label_id)
        used_records.append(item)

    except Exception as e:
        print("Skipped:", item.get("video_path", "unknown"))
        print("Reason:", e)

X = np.array(X, dtype=np.float32)
y = np.array(y, dtype=np.int64)

print("Final X shape:", X.shape)
print("Final y shape:", y.shape)

if len(X) == 0:
    raise RuntimeError("No features were extracted. Check downloaded videos.")

# -------------------------
# Check class counts
# -------------------------
unique_labels, label_counts = np.unique(y, return_counts=True)

print("\nLabel counts:")
for label_id, count in zip(unique_labels, label_counts):
    print(le_subset.inverse_transform([label_id])[0], ":", count)

# Keep only classes with at least 2 samples
valid_label_ids = set(
    label_id
    for label_id, count in zip(unique_labels, label_counts)
    if count >= 2
)

mask = np.array([label_id in valid_label_ids for label_id in y])

X = X[mask]
y = y[mask]
used_records = [record for record, keep in zip(used_records, mask) if keep]

print("\nAfter removing classes with <2 samples:")
print("X shape:", X.shape)
print("y shape:", y.shape)

if len(set(y)) < 2:
    raise RuntimeError(
        "Need at least 2 classes with at least 2 videos each. "
        "Increase metadata scan/download settings in Cell 1."
    )

# -------------------------
# Train / validation split
# -------------------------
unique_labels, label_counts = np.unique(y, return_counts=True)
can_stratify = np.all(label_counts >= 2)

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y if can_stratify else None
)

print("\nTrain X:", X_train.shape)
print("Validation X:", X_val.shape)
print("Train y:", y_train.shape)
print("Validation y:", y_val.shape)

# -------------------------
# Train classifier
# -------------------------
model_clf = LogisticRegression(
    max_iter=1000,
    solver="lbfgs",
    class_weight="balanced"
)

model_clf.fit(X_train, y_train)

print("\nClassifier trained successfully.")

# ============================================================
# CELL 3: TESTING + METRICS + ERROR ANALYSIS + SAVE MODEL
# ============================================================

import joblib
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    top_k_accuracy_score
)

# -------------------------
# Predictions
# -------------------------
pred = model_clf.predict(X_val)
proba = model_clf.predict_proba(X_val)

# -------------------------
# Main metrics
# -------------------------
accuracy = accuracy_score(y_val, pred)

precision_macro = precision_score(
    y_val,
    pred,
    average="macro",
    zero_division=0
)

recall_macro = recall_score(
    y_val,
    pred,
    average="macro",
    zero_division=0
)

f1_macro = f1_score(
    y_val,
    pred,
    average="macro",
    zero_division=0
)

precision_weighted = precision_score(
    y_val,
    pred,
    average="weighted",
    zero_division=0
)

recall_weighted = recall_score(
    y_val,
    pred,
    average="weighted",
    zero_division=0
)

f1_weighted = f1_score(
    y_val,
    pred,
    average="weighted",
    zero_division=0
)

top2_acc = top_k_accuracy_score(
    y_val,
    proba,
    k=2,
    labels=model_clf.classes_
)

# Top-3
if len(model_clf.classes_) >= 3:
    top3_acc = top_k_accuracy_score(
        y_val,
        proba,
        k=3,
        labels=model_clf.classes_
    )
else:
    top3_acc = None

print("========== METRICS ==========")
print(f"Accuracy:           {accuracy:.4f}")
print(f"Precision macro:    {precision_macro:.4f}")
print(f"Recall macro:       {recall_macro:.4f}")
print(f"F1-score macro:     {f1_macro:.4f}")
print(f"Precision weighted: {precision_weighted:.4f}")
print(f"Recall weighted:    {recall_weighted:.4f}")
print(f"F1-score weighted:  {f1_weighted:.4f}")
print(f"Top-2 Accuracy:     {top2_acc:.4f}")

if top3_acc is not None:
    print(f"Top-3 Accuracy:     {top3_acc:.4f}")

# -------------------------
# Classification report
# -------------------------
labels_present = sorted(list(set(y_val) | set(pred)))
target_names_present = [
    str(le_subset.inverse_transform([i])[0])
    for i in labels_present
]

from sklearn.metrics import precision_recall_fscore_support

print("\n========== PER-CLASS METRICS ==========")

precision_per_class, recall_per_class, f1_per_class, _ = precision_recall_fscore_support(
    y_val,
    pred,
    labels=labels_present,
    zero_division=0
)

for class_name, precision, recall, f1 in zip(
    target_names_present,
    precision_per_class,
    recall_per_class,
    f1_per_class
):
    print(f"{class_name}:")
    print(f"  Precision: {precision:.4f}")
    print(f"  Recall:    {recall:.4f}")
    print(f"  F1-score:  {f1:.4f}")

# -------------------------
# Confusion matrix
# -------------------------
cm = confusion_matrix(
    y_val,
    pred,
    labels=labels_present
)

plt.figure(figsize=(8, 6))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    xticklabels=target_names_present,
    yticklabels=target_names_present
)

plt.title("Confusion Matrix")
plt.xlabel("Predicted label")
plt.ylabel("True label")
plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

# -------------------------
# Error analysis: wrong classifications
# -------------------------
print("\n========== ERROR ANALYSIS: WRONG CLASSIFICATIONS ==========")

wrong_indices = np.where(pred != y_val)[0]

print("Number of validation samples:", len(y_val))
print("Number of wrong predictions:", len(wrong_indices))
print("Number of correct predictions:", len(y_val) - len(wrong_indices))

if len(wrong_indices) == 0:
    print("No wrong classifications found.")
else:
    max_errors_to_show = 10

    print(f"\nShowing up to {max_errors_to_show} wrong classifications:\n")

    for count, idx in enumerate(wrong_indices[:max_errors_to_show], start=1):
        true_id = y_val[idx]
        pred_id = pred[idx]

        true_label = le_subset.inverse_transform([true_id])[0]
        pred_label = le_subset.inverse_transform([pred_id])[0]

        sample_proba = proba[idx]

        class_probabilities = []

        for class_id, probability in zip(model_clf.classes_, sample_proba):
            class_name = le_subset.inverse_transform([class_id])[0]
            class_probabilities.append((class_name, probability))

        class_probabilities = sorted(
            class_probabilities,
            key=lambda x: x[1],
            reverse=True
        )

        print(f"Error #{count}")
        print("Validation index:", idx)
        print("True label:", true_label)
        print("Predicted label:", pred_label)

        print("Top probabilities:")
        for class_name, probability in class_probabilities[:3]:
            print(f"  {class_name}: {probability:.4f}")

        print("-" * 40)

# -------------------------
# Per-class error summary
# -------------------------
print("\n========== PER-CLASS ERROR SUMMARY ==========")

for label_id in labels_present:
    label_name = le_subset.inverse_transform([label_id])[0]

    total_for_class = np.sum(y_val == label_id)
    wrong_for_class = np.sum((y_val == label_id) & (pred != label_id))
    correct_for_class = total_for_class - wrong_for_class

    if total_for_class > 0:
        class_error_rate = wrong_for_class / total_for_class
    else:
        class_error_rate = 0

    print(
        f"{label_name}: "
        f"total={total_for_class}, "
        f"correct={correct_for_class}, "
        f"wrong={wrong_for_class}, "
        f"error_rate={class_error_rate:.4f}"
    )

# -------------------------
# Test on one video
# -------------------------
sample_index = 0

sample_record = used_records[sample_index]
sample_video_path = sample_record["video_path"]
sample_true_label = sample_record["label"]

sample_features = get_videomae_features(sample_video_path).reshape(1, -1)

sample_pred_id = model_clf.predict(sample_features)[0]
sample_pred_label = le_subset.inverse_transform([sample_pred_id])[0]

sample_proba = model_clf.predict_proba(sample_features)[0]

class_probabilities = []

for class_id, probability in zip(model_clf.classes_, sample_proba):
    class_name = le_subset.inverse_transform([class_id])[0]
    class_probabilities.append((class_name, probability))

class_probabilities = sorted(
    class_probabilities,
    key=lambda x: x[1],
    reverse=True
)

print("\n========== SINGLE VIDEO TEST ==========")
print("Video path:", sample_video_path)
print("True label:", sample_true_label)
print("Predicted label:", sample_pred_label)

print("\nClass probabilities for single video:")
for class_name, probability in class_probabilities:
    print(f"{class_name}: {probability:.4f}")

# -------------------------
# Save model and artifacts
# -------------------------
joblib.dump(model_clf, "howto100m_videomae_logistic_regression.pkl")
joblib.dump(le_subset, "howto100m_label_encoder.pkl")
joblib.dump(used_records, "howto100m_used_records.pkl")

np.save("howto100m_features.npy", X)
np.save("howto100m_labels.npy", y)

print("\n========== SAVED FILES ==========")
print("- howto100m_videomae_logistic_regression.pkl")
print("- howto100m_label_encoder.pkl")
print("- howto100m_used_records.pkl")
print("- howto100m_features.npy")
print("- howto100m_labels.npy")
