# -*- coding: utf-8 -*-
"""fridge_recipe_qwen_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uCHSeebVcJS4OfE2FAd7rgZEHEYCGj6G
"""

# ===== начало ячейки 1: установка зависимостей =====

# 1. Установка зависимостей для Google Colab


!pip -q install -U transformers accelerate bitsandbytes gigachat

# Утилиты для обработки картинок / видео в Qwen-VL
!pip -q install "qwen-vl-utils[decord]==0.0.8"

# Возвращаем версии, совместимые с Colab
!pip -q install "pandas==2.2.2" "pillow<12.0,>=8.0" matplotlib openpyxl seaborn


print("Установка завершена. Теперь перезапустите Runtime: Runtime → Restart session")

# ===== конец ячейки 1 =====

# ===== начало ячейки 2: импорты, VLM, фото и функция распознавания =====

# 2. Импорты и базовые настройки

import os
import re
import gc
import json
import ast
from collections import Counter

import torch
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image
from IPython.display import display, Markdown

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
DTYPE = torch.float16 if torch.cuda.is_available() else torch.float32

print("Device:", DEVICE)
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# 5. Загружаем VLM: Qwen2.5-VL для распознавания продуктов

import torch
from transformers import Qwen2_5_VLForConditionalGeneration, AutoProcessor

VLM_MODEL_ID = "Qwen/Qwen2.5-VL-3B-Instruct"

# Ограничиваем размер картинки, иначе Colab T4 ловит CUDA out of memory.
min_pixels = 256 * 28 * 28
max_pixels = 768 * 28 * 28   # безопаснее для T4. Можно попробовать 1024 * 28 * 28

vlm_processor = AutoProcessor.from_pretrained(
    VLM_MODEL_ID,
    min_pixels=min_pixels,
    max_pixels=max_pixels,
)

vlm_model = Qwen2_5_VLForConditionalGeneration.from_pretrained(
    VLM_MODEL_ID,
    torch_dtype=torch.float16,
    device_map="auto",
)

vlm_model.eval()

print("VLM загружена:", VLM_MODEL_ID)

# 4. Загрузка фото

from google.colab import drive
drive.mount('/content/drive')

image_paths = [
    "/content/ph/1.jpg",
    "/content/ph/2.jpg",
    "/content/ph/3.jpg",
    "/content/ph/4.jpg",
    "/content/ph/5.jpg",
    "/content/ph/6.jpg",
    "/content/ph/7.jpg",
    "/content/ph/8.jpg",
    "/content/ph/9.jpg",
    "/content/ph/10.jpg",
    "/content/ph/11.jpg",
    "/content/ph/12.jpg",
    "/content/ph/13.jpg",
    "/content/ph/14.jpg",
    "/content/ph/15.jpg",
    "/content/ph/16.jpg",
    "/content/ph/17.jpg",
    "/content/ph/18.jpg",
    "/content/ph/19.jpg",
]

print("Изображения:")
for p in image_paths:
    print("-", p)

# 5. Посмотрим первое загруженное фото

if image_paths:
    img = Image.open(image_paths[0]).convert("RGB")
    preview_width = min(700, img.width)
    display(img.resize((preview_width, int(img.height * preview_width / img.width))))
else:
    print("Сначала загрузите изображения в предыдущей ячейке.")

# 6. Функция распознавания продуктов на фото

import json
import re
import gc
import torch



def extract_json(text):
    """
    Пытаемся достать JSON из ответа модели.
    Если модель вернула текст вокруг JSON, вырезаем первый JSON-массив.
    """
    text = text.strip()

    try:
        return json.loads(text)
    except:
        pass

    match = re.search(r"\[.*\]", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(0))
        except:
            pass

    return []


def move_inputs_to_model_device(inputs):
    moved = {}

    for key, value in inputs.items():
        value = value.to(vlm_model.device)

        if torch.cuda.is_available() and torch.is_floating_point(value):
            value = value.to(torch.float16)

        moved[key] = value

    return moved


def detect_products(image_path, max_new_tokens=512):
    prompt = """
Ты анализируешь фото холодильника или продуктовой полки.

Найди только реально видимые продукты питания.
Не выдумывай продукты.
Если продукт плохо виден, укажи низкую уверенность.

Верни ответ строго в JSON-формате без пояснений:

[
  {
    "name": "название продукта на русском",
    "category": "овощи / фрукты / молочные / мясо / рыба / напитки / крупы / соусы / другое",
    "confidence": 0.0
  }
]
"""

    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image", "image": image_path},
                {"type": "text", "text": prompt},
            ],
        }
    ]

    text = vlm_processor.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    image_inputs, video_inputs = process_vision_info(messages)

    inputs = vlm_processor(
        text=[text],
        images=image_inputs,
        videos=video_inputs,
        padding=True,
        return_tensors="pt",
    ).to(vlm_model.device)

    with torch.inference_mode():
        generated_ids = vlm_model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            use_cache=False,   # меньше расход памяти
        )

    generated_ids_trimmed = [
        out_ids[len(in_ids):]
        for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
    ]

    output_text = vlm_processor.batch_decode(
        generated_ids_trimmed,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False,
    )[0]

    products = extract_json(output_text)

    # чистим память после каждого изображения
    del inputs, generated_ids, generated_ids_trimmed
    gc.collect()
    torch.cuda.empty_cache()

    return {
        "image_path": image_path,
        "raw_output": output_text,
        "products": products,
    }

# ===== конец ячейки 2 =====

# ===== начало ячейки 3: запуск распознавания фото =====

# 7. Запускаем распознавание для всех загруженных фото

import gc
import torch

detections = []

for path in image_paths:
    print(f"\nРаспознаю: {path}")

    try:
        det = detect_products(path)
        detections.append(det)

        products = det["products"]

        if products:
            print("Продукты:")
            for item in products:
                print(
                    "-",
                    item.get("name", "без названия"),
                    "| категория:",
                    item.get("category", "не указана"),
                    "| confidence:",
                    item.get("confidence", "не указана"),
                )
        else:
            print("Продукты: не найдены")
            print("Сырой ответ модели:")
            print(det["raw_output"])

    except torch.cuda.OutOfMemoryError:
        print("CUDA out of memory на изображении:", path)
        print("Пропускаю это изображение. Попробуйте уменьшить max_pixels до 512 * 28 * 28.")

        gc.collect()
        torch.cuda.empty_cache()

    except Exception as e:
        print("Ошибка на изображении:", path)
        print(type(e).__name__, e)

    gc.collect()
    torch.cuda.empty_cache()

# ===== конец ячейки 3 =====

# ===== начало ячейки 4: восстановление оборванного JSON и сбор pred_df =====



import pandas as pd
import json
import re


def clean_output(text):
    """
    Убираем markdown-разметку и лишние символы.
    """
    if text is None:
        return ""

    text = str(text)

    text = text.replace("```json", "")
    text = text.replace("```JSON", "")
    text = text.replace("```", "")

    return text.strip()


def extract_complete_json_objects(text):
    """
    Достаёт все завершённые JSON-объекты {...} из текста.
    Работает даже если общий список [...] оборван.
    """
    text = clean_output(text)

    objects = []
    stack = 0
    start = None

    for i, ch in enumerate(text):
        if ch == "{":
            if stack == 0:
                start = i
            stack += 1

        elif ch == "}":
            stack -= 1
            if stack == 0 and start is not None:
                obj_text = text[start:i + 1]
                objects.append(obj_text)
                start = None

    return objects


def parse_product_object(obj_text):
    """
    Парсит один объект продукта.
    Если json.loads не сработал, достаёт поля регулярками.
    """
    obj_text = obj_text.strip()


    try:
        obj = json.loads(obj_text)
        if isinstance(obj, dict):
            return obj
    except Exception:
        pass

    # 2. Исправляем частые проблемы
    fixed = obj_text
    fixed = fixed.replace("'", '"')
    fixed = fixed.replace("“", '"').replace("”", '"')
    fixed = fixed.replace("«", '"').replace("»", '"')
    fixed = re.sub(r",\s*}", "}", fixed)

    try:
        obj = json.loads(fixed)
        if isinstance(obj, dict):
            return obj
    except Exception:
        pass

    # 3. Fallback: достаём name/category/confidence регулярками
    name_match = re.search(r'"name"\s*:\s*"([^"]+)"', obj_text)
    category_match = re.search(r'"category"\s*:\s*"([^"]+)"', obj_text)
    confidence_match = re.search(r'"confidence"\s*:\s*([0-9.]+)', obj_text)

    if not name_match:
        return None

    name = name_match.group(1).strip()
    category = category_match.group(1).strip() if category_match else "другое"

    try:
        confidence = float(confidence_match.group(1)) if confidence_match else 1.0
    except Exception:
        confidence = 1.0

    return {
        "name": name,
        "category": category,
        "confidence": confidence
    }


def extract_products_from_raw_output(raw_output):
    """
    Главная функция: получает raw_output модели и возвращает список продуктов.
    """
    text = clean_output(raw_output)

    product_objects = extract_complete_json_objects(text)

    products = []

    for obj_text in product_objects:
        product = parse_product_object(obj_text)

        if product is None:
            continue

        name = str(product.get("name", "")).strip()

        if not name:
            continue

        category = str(product.get("category", "другое")).strip()

        try:
            confidence = float(product.get("confidence", 1.0))
        except Exception:
            confidence = 1.0

        products.append({
            "name": name,
            "category": category,
            "confidence": confidence
        })

    # Убираем дубли
    unique_products = []
    seen = set()

    for product in products:
        key = product["name"].lower()

        if key not in seen:
            unique_products.append(product)
            seen.add(key)

    return unique_products


def product_confidence(item, default=1.0):
    try:
        return float(item.get("confidence", default))
    except Exception:
        return default


def ingredient_names(det, min_confidence=0.0):
    """
    Возвращает названия продуктов из det.
    """
    products = det.get("products", [])

    names = []

    for item in products:
        if isinstance(item, dict):
            if product_confidence(item) < min_confidence:
                continue

            name = str(item.get("name", "")).strip()
            if name:
                names.append(name)
        elif isinstance(item, str):
            name = item.strip()
            if name:
                names.append(name)

    # Убираем дубли
    names = list(dict.fromkeys(names))

    return names


def products_to_eval_text(products, min_confidence=0.0):
    names = []

    for item in products:
        if isinstance(item, dict):
            if product_confidence(item) < min_confidence:
                continue

            name = str(item.get("name", "")).strip()
        else:
            name = str(item).strip()

        if name and name not in names:
            names.append(name)

    return ". ".join(names)


# 8.1. Восстанавливаем продукты из raw_output и печатаем результат в нормальном виде


if "detections" not in globals() or not detections:
    raise NameError(
        "detections не найден. Сначала запустите ячейку распознавания фото."
    )

repaired_rows = []

for i, det in enumerate(detections):
    raw_output = det.get("raw_output", "")
    products = extract_products_from_raw_output(raw_output)

    if products:
        det["products"] = products
    else:
        products = det.get("products", [])

    print(f"\nРаспознаю: {det.get('image_path', '')}")

    if products:
        print("Продукты:")

        for item in products:
            if isinstance(item, dict):
                name = str(item.get("name", "без названия")).strip()
                category = str(item.get("category", "не указана")).strip()
                confidence = product_confidence(item)
            else:
                name = str(item).strip()
                category = "не указана"
                confidence = 1.0

            print(f"- {name} | категория: {category} | confidence: {confidence}")
    else:
        print("Продукты: не найдены")
        print("Сырой ответ модели:")
        print(raw_output)

    repaired_rows.append({
        "index": i,
        "image_path": det.get("image_path", ""),
        "predicted_products": products_to_eval_text(products),
        "num_products": len(products),
        "raw_output": str(raw_output)[:700]
    })

pred_df = pd.DataFrame(repaired_rows)

print("\npred_df пересобран:")
display(pred_df[["index", "image_path", "predicted_products", "num_products"]])


# Восстанавливаем products у всех detections прямо из raw_output
for det in detections:
    raw_output = det.get("raw_output", "")
    products = extract_products_from_raw_output(raw_output)
    det["products"] = products


# Собираем таблицу
rows = []

for i, det in enumerate(detections):
    products = det.get("products", [])

    names = []
    uncertain_items = []
    categories = []

    for item in products:
        name = str(item.get("name", "")).strip()
        category = str(item.get("category", "другое")).strip()

        confidence = product_confidence(item)

        if name:
            names.append(name)
            categories.append(f"{name}: {category}")

            if confidence < 0.6:
                uncertain_items.append(name)

    rows.append({
        "index": i,
        "image_path": det.get("image_path", ""),
        "predicted_products": products_to_eval_text(products),
        "uncertain": ", ".join(uncertain_items),
        "categories": "; ".join(categories),
        "num_products": len(names),
        "raw_output": str(det.get("raw_output", ""))[:700]
    })


pred_df = pd.DataFrame(rows)

print("Готово.")
print("Всего изображений:", len(pred_df))
print("Изображений, где найдены продукты:", int((pred_df["num_products"] > 0).sum()))
print("Изображений без продуктов:", int((pred_df["num_products"] == 0).sum()))

display(pred_df)


# Показываем только проблемные строки, если они остались
empty_df = pred_df[pred_df["num_products"] == 0]

if len(empty_df) > 0:
    print("\nОстались изображения, где продукты не удалось извлечь:")
    display(empty_df[["index", "image_path", "raw_output"]])
else:
    print("\nВсе строки успешно обработаны.")

# ===== конец ячейки 4 =====

# ===== начало ячейки 5: LLM и генерация рецептов =====

"""## Часть B. Генерация рецептов с Qwen2.5-1.5B-Instruct

памяти нам не хватает поэжту чистим ее после распознавания продуктов 

"""

# 9. Освобождаем память перед загрузкой LLM

try:
    del vlm_model
    del vlm_processor
except Exception:
    pass

gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()

print("Память очищена.")

# 10. Загрузка Qwen2.5-1.5B-Instruct

from transformers import AutoModelForCausalLM, AutoTokenizer

LLM_MODEL_ID = "Qwen/Qwen2.5-1.5B-Instruct"

llm_tokenizer = AutoTokenizer.from_pretrained(LLM_MODEL_ID)
llm_model = AutoModelForCausalLM.from_pretrained(
    LLM_MODEL_ID,
    torch_dtype="auto",
    device_map="auto"
)

print("LLM loaded:", LLM_MODEL_ID)

# 11. Функция генерации рецептов

def build_recipe_prompt(ingredients, servings=2, preferences=""):
    ingredients_text = ", ".join(ingredients) if ingredients else "ингредиенты не распознаны"

    pref_text = preferences.strip()
    if not pref_text:
        pref_text = "нет особых ограничений"

    return f"""
У тебя есть список продуктов, распознанных на фото холодильника или продуктовой полки:

{ingredients_text}

Пожелания пользователя: {pref_text}
Количество порций: {servings}

Составь 2–3 практичных рецепта на русском языке.

Требования:
0. Невыдумывай рецепты
1. Используй в основном продукты из списка.
2. Дополнительно можно использовать только базовые вещи: вода, соль, перец, растительное масло, базовые сухие специи.
3. МОжешь предлагать продукты, которых нет в списке. Если очень нужен дополнительный продукт, пометь его как "опционально".
4. Если список продуктов скудный, предложи максимально простые блюда.
5. Можешь предлагать продукты не указанные в списке.
6. Для каждого рецепта укажи:
   - название;
   - какие распознанные продукты используются;
   - базовые добавки;
   - время приготовления;
   - пошаговый способ;
   - короткую заметку, что можно заменить или убрать.


Формат ответа:

## 1. Название
**Используем:** ...
**Базовые добавки:** ...
**Время:** ...
**Шаги:**
1. ...
2. ...
**Замены:** ...

## 2. ...
"""


@torch.inference_mode()
def generate_recipes_from_products(ingredients, servings=2, preferences="", max_new_tokens=900):
    messages = [
        {
            "role": "system",
            "content": (
                "Ты аккуратный кулинарный ассистент. "
                "Ты не должен придумывать обязательные ингредиенты, которых нет в списке. "
                "Отвечай понятно, по-русски."
            )
        },
        {
            "role": "user",
            "content": build_recipe_prompt(ingredients, servings=servings, preferences=preferences)
        }
    ]

    text = llm_tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = llm_tokenizer([text], return_tensors="pt").to(llm_model.device)

    output_ids = llm_model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=True,
        temperature=0.7,
        top_p=0.9,
        repetition_penalty=1.05,
    )

    generated_ids = output_ids[0][inputs.input_ids.shape[-1]:]
    answer = llm_tokenizer.decode(generated_ids, skip_special_tokens=True)
    return answer.strip()


def normalize_eval_text(text):
    text = "" if text is None else str(text).lower().replace("ё", "е")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def split_eval_items(text):
    if pd.isna(text):
        return []

    parts = re.split(r"[.;,\n]+", str(text))
    items = []

    for part in parts:
        item = normalize_eval_text(part).strip('"').strip("'").strip()
        if item and item not in items:
            items.append(item)

    return items


def score_recipe_ingredients(recipe_text, input_products, invented_required_products=""):
    recipe_norm = normalize_eval_text(recipe_text)

    input_products_norm = []
    for product in input_products:
        product_norm = normalize_eval_text(product)
        if product_norm and product_norm not in input_products_norm:
            input_products_norm.append(product_norm)

    used_products = [
        product
        for product in input_products_norm
        if product in recipe_norm
    ]

    not_used_products = [
        product
        for product in input_products_norm
        if product not in used_products
    ]

    invented_products = split_eval_items(invented_required_products)

    ingredient_recall = (
        len(used_products) / len(input_products_norm)
        if input_products_norm
        else 1.0
    )
    ingredient_precision = (
        len(used_products) / (len(used_products) + len(invented_products))
        if used_products or invented_products
        else 1.0
    )
    ingredient_f1 = (
        2 * ingredient_precision * ingredient_recall / (ingredient_precision + ingredient_recall)
        if ingredient_precision + ingredient_recall
        else 0.0
    )

    return {
        "used_input_products": ". ".join(used_products),
        "not_used_input_products": ". ".join(not_used_products),
        "invented_required_products": ". ".join(invented_products),
        "ingredient_precision": ingredient_precision,
        "ingredient_recall": ingredient_recall,
        "ingredient_f1": ingredient_f1,
        "num_input_products": len(input_products_norm),
        "num_used_input_products": len(used_products),
        "num_invented_required_products": len(invented_products),
    }

# 12. Генерируем рецепты для первого фото

from IPython.display import display, Markdown

IMAGE_INDEX = 0
SERVINGS = 2
PREFERENCES = "Без мяса"  #  "без мяса", "быстро, до 20 минут", "что-то на завтрак"
INVENTED_REQUIRED_PRODUCTS = ""
HUMAN_RECIPE_SCORE_1_5 = ""

if not detections:
    print("Нет результатов VLM. Сначала запустите распознавание продуктов.")
else:
    selected_detection = detections[IMAGE_INDEX]

    selected_products = ingredient_names(selected_detection)

    print("Фото:", selected_detection["image_path"])
    print("Ингредиенты:", ", ".join(selected_products))

    recipes = generate_recipes_from_products(
        selected_products,
        servings=SERVINGS,
        preferences=PREFERENCES
    )

    display(Markdown(recipes))

    recipe_eval = score_recipe_ingredients(
        recipe_text=recipes,
        input_products=selected_products,
        invented_required_products=INVENTED_REQUIRED_PRODUCTS
    )

    recipe_eval_df = pd.DataFrame([
        {
            "model": LLM_MODEL_ID,
            "image_path": selected_detection["image_path"],
            "input_products": ". ".join(selected_products),
            "recipe_text": recipes,
            **recipe_eval,
            "human_recipe_score_1_5": HUMAN_RECIPE_SCORE_1_5
        }
    ])

    recipe_eval_df.to_csv("recipe_eval_results.csv", index=False, encoding="utf-8-sig")

    print("Recipe eval:")
    display(recipe_eval_df.drop(columns=["recipe_text"]))

# 13. Сохраняем результат в markdown-файл

if detections:
    output_md = f'''# Рецепты по фото

**Фото:** {selected_detection["image_path"]}

**Распознанные продукты:** {", ".join(selected_products)}

---

{recipes}
'''
    with open("recipes_result.md", "w", encoding="utf-8") as f:
        f.write(output_md)

    print("Сохранено: recipes_result.md")

# ===== конец ячейки 5 =====

# ===== начало ячейки 6: создание и загрузка ручной разметки =====

"""## Часть C. Eval на 10–20 фото

Идея eval: для каждого фото модель даёт `predicted_products`, а человек заполняет `true_products`.

Пример формата в `true_products`:

```text
молоко, яйца, сыр, огурцы, яблоки
```

Затем считаем:
- **missed** = есть в ручной разметке, но нет у модели;
- **hallucinated** = модель назвала, но на фото этого нет;
- **precision** = доля предсказаний, которые верны;
- **recall** = доля реальных продуктов, которые модель нашла.

"""

# 14. Создаём шаблон для ручной проверки

if "pred_df" not in globals():
    if "detections" not in globals() or not detections:
        raise NameError(
            "pred_df не найден. Сначала запустите ячейки распознавания продуктов, "
            "где создаются detections и pred_df."
        )

    rows = []

    for i, det in enumerate(detections):
        products = det.get("products", [])

        rows.append({
            "index": i,
            "image_path": det.get("image_path", ""),
            "predicted_products": products_to_eval_text(products),
            "num_products": len(products),
            "raw_output": str(det.get("raw_output", ""))[:700]
        })

    pred_df = pd.DataFrame(rows)
    print("pred_df не был найден, поэтому он пересобран из detections.")

eval_template = pred_df[["index", "image_path", "predicted_products"]].copy()
eval_template["true_products"] = ""  # заполнить вручную
eval_template.to_csv("eval_template.csv", index=False, encoding="utf-8-sig")

eval_template

# 15. Скачайте CSV, заполните true_products вручную и загрузите обратно как eval_filled.csv

from google.colab import files

files.download("eval_template.csv")
print("После заполнения загрузите файл обратно в Colab и назовите его eval_filled.csv")

# 16. Загрузка заполненного файла eval_filled.csv
# Запустите эту ячейку после ручного заполнения true_products.

uploaded_eval = files.upload()
print(uploaded_eval.keys())

from google.colab import files
import pandas as pd

eval_file = list(uploaded_eval.keys())[0]
eval_df = pd.read_csv(eval_file)

eval_df.head()

# ===== конец ячейки 6 =====

eval_df.shape

# ===== начало ячейки 7: базовые метрики распознавания =====

# 17. Метрики eval

# - столбцы в CSV разделяются запятыми: ,
# - короче продукты внутри ячейки разделяются точкой: .

import pandas as pd
import re


def split_products(text):
    """
    Делит продукты внутри одной ячейки по точке.
    Пример:
    'яблоки. апельсины. болгарский перец'
    ->
    {'яблоки', 'апельсины', 'болгарский перец'}
    """
    if pd.isna(text):
        return set()

    text = str(text).lower().replace("ё", "е")


    parts = re.split(r"[.;,\n]+", text)

    items = []

    for p in parts:
        p = p.strip()


        p = re.sub(r"\s+", " ", p)

        p = p.strip('"').strip("'").strip()

        if p:
            items.append(p)

    return set(items)


def score_row(predicted_text, true_text):
    pred = split_products(predicted_text)
    true = split_products(true_text)

    missed = sorted(true - pred)
    hallucinated = sorted(pred - true)
    correct = sorted(pred & true)

    precision = len(correct) / len(pred) if pred else (1.0 if not true else 0.0)
    recall = len(correct) / len(true) if true else (1.0 if not pred else 0.0)
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0

    return {
        "correct": ". ".join(correct),
        "missed": ". ".join(missed),
        "hallucinated": ". ".join(hallucinated),
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "num_predicted": len(pred),
        "num_true": len(true),
        "num_correct": len(correct),
        "num_missed": len(missed),
        "num_hallucinated": len(hallucinated),
    }


def build_score_df(source_df, predicted_col="predicted_products"):
    scores = []

    for _, row in source_df.iterrows():
        scores.append(
            score_row(
                row.get(predicted_col, ""),
                row.get("true_products", "")
            )
        )

    return pd.concat(
        [
            source_df.reset_index(drop=True),
            pd.DataFrame(scores).reset_index(drop=True)
        ],
        axis=1
    )



try:
    eval_df
    print("Использую уже загруженный eval_df")
except NameError:
    eval_path = "eval_filled.csv"

    # Столбцы разделены запятыми
    eval_df = pd.read_csv(eval_path, sep=",", encoding="utf-8-sig")

print("Колонки:", list(eval_df.columns))

required_cols = ["predicted_products", "true_products"]

missing_cols = [col for col in required_cols if col not in eval_df.columns]
if missing_cols:
    raise ValueError(f"В таблице нет нужных колонок: {missing_cols}")

score_df = build_score_df(eval_df)

summary = {
    "num_images": len(score_df),
    "mean_precision": score_df["precision"].mean(),
    "mean_recall": score_df["recall"].mean(),
    "mean_f1": score_df["f1"].mean(),
    "total_predicted": score_df["num_predicted"].sum(),
    "total_true": score_df["num_true"].sum(),
    "total_correct": score_df["num_correct"].sum(),
    "total_missed": score_df["num_missed"].sum(),
    "total_hallucinated": score_df["num_hallucinated"].sum(),
}

print("Summary:")
for k, v in summary.items():
    if isinstance(v, float):
        print(f"{k}: {v:.3f}")
    else:
        print(f"{k}: {v}")

score_df.to_csv("eval_results.csv", index=False, encoding="utf-8-sig")

display(score_df)

# ===== конец ячейки 7 =====

# ===== начало ячейки 8: confidence-пороги, графики, файлы и отчет =====

# 17.1. Метрики при разных порогах confidence

CONFIDENCE_THRESHOLDS = [round(i / 10, 1) for i in range(0, 11)]


def get_detection_products_for_eval_row(row, fallback_index):
    if "detections" not in globals() or not detections:
        return None

    image_path = str(row.get("image_path", "")).strip()

    if image_path:
        for det in detections:
            if str(det.get("image_path", "")).strip() == image_path:
                return det.get("products", [])

    if "index" in row and not pd.isna(row.get("index")):
        try:
            det_index = int(row.get("index"))
            if 0 <= det_index < len(detections):
                return detections[det_index].get("products", [])
        except Exception:
            pass

    if 0 <= fallback_index < len(detections):
        return detections[fallback_index].get("products", [])

    return None


threshold_summaries = []
threshold_details = []

if "detections" in globals() and detections:
    for threshold in CONFIDENCE_THRESHOLDS:
        threshold_eval_df = eval_df.copy()

        threshold_predictions = []

        for row_index, row in threshold_eval_df.iterrows():
            products = get_detection_products_for_eval_row(row, row_index)

            if products is None:
                predicted_text = row.get("predicted_products", "")
            else:
                predicted_text = products_to_eval_text(
                    products,
                    min_confidence=threshold
                )

            threshold_predictions.append(predicted_text)

        threshold_eval_df["confidence_threshold"] = threshold
        threshold_eval_df["predicted_products_at_threshold"] = threshold_predictions

        threshold_score_df = build_score_df(
            threshold_eval_df,
            predicted_col="predicted_products_at_threshold"
        )

        threshold_details.append(threshold_score_df)

        threshold_summaries.append({
            "model": VLM_MODEL_ID if "VLM_MODEL_ID" in globals() else "current_vlm",
            "confidence_threshold": threshold,
            "mean_precision": threshold_score_df["precision"].mean(),
            "mean_recall": threshold_score_df["recall"].mean(),
            "mean_f1": threshold_score_df["f1"].mean(),
            "total_predicted": threshold_score_df["num_predicted"].sum(),
            "total_true": threshold_score_df["num_true"].sum(),
            "total_correct": threshold_score_df["num_correct"].sum(),
            "total_missed": threshold_score_df["num_missed"].sum(),
            "total_hallucinated": threshold_score_df["num_hallucinated"].sum(),
        })

    threshold_summary_df = pd.DataFrame(threshold_summaries)
    threshold_detail_df = pd.concat(threshold_details, ignore_index=True)

    threshold_summary_df.to_csv(
        "eval_threshold_summary.csv",
        index=False,
        encoding="utf-8-sig"
    )
    threshold_detail_df.to_csv(
        "eval_threshold_details.csv",
        index=False,
        encoding="utf-8-sig"
    )

    print("Confidence threshold summary:")
    display(threshold_summary_df)

    plt.figure(figsize=(10, 5))
    plt.plot(
        threshold_summary_df["confidence_threshold"],
        threshold_summary_df["mean_precision"],
        marker="o",
        label="mean_precision"
    )
    plt.plot(
        threshold_summary_df["confidence_threshold"],
        threshold_summary_df["mean_recall"],
        marker="o",
        label="mean_recall"
    )
    plt.plot(
        threshold_summary_df["confidence_threshold"],
        threshold_summary_df["mean_f1"],
        marker="o",
        label="mean_f1"
    )
    plt.xlabel("Confidence threshold")
    plt.ylabel("Mean metric")
    plt.ylim(0, 1.05)
    plt.title("Mean precision / recall / f1 by confidence threshold")
    plt.legend()
    plt.grid(True)
    plt.show()
else:
    print("Нет detections, поэтому метрики по confidence threshold не рассчитаны.")

# 18. Агрегируем самые частые пропуски и галлюцинации

def counter_from_column(series):
    c = Counter()
    for text in series.fillna(""):
        for item in split_products(text):
            c[item] += 1
    return c

missed_counter = counter_from_column(score_df["missed"])
hall_counter = counter_from_column(score_df["hallucinated"])

print("Топ пропущенных продуктов:")
for item, count in missed_counter.most_common(20):
    print(f"{item}: {count}")

print("\\nТоп придуманных продуктов:")
for item, count in hall_counter.most_common(20):
    print(f"{item}: {count}")

# 19. Визуализация precision / recall / f1 по изображениям

plot_df = score_df.copy()
plot_df["image_num"] = range(1, len(plot_df) + 1)

plt.figure(figsize=(10, 5))
plt.plot(plot_df["image_num"], plot_df["precision"], marker="o", label="precision")
plt.plot(plot_df["image_num"], plot_df["recall"], marker="o", label="recall")
plt.plot(plot_df["image_num"], plot_df["f1"], marker="o", label="f1")
plt.xlabel("Номер изображения")
plt.ylabel("Метрика")
plt.ylim(0, 1.05)
plt.title("Качество распознавания продуктов по фото")
plt.legend()
plt.grid(True)
plt.show()

# 20. Скачивание результатов eval

files.download("eval_results.csv")
print("Файл eval_results.csv содержит missed, hallucinated, precision, recall, f1 по каждому фото.")

if os.path.exists("eval_threshold_summary.csv"):
    files.download("eval_threshold_summary.csv")
    print("Файл eval_threshold_summary.csv содержит средние precision, recall, f1 по confidence-порогам.")

if os.path.exists("eval_threshold_details.csv"):
    files.download("eval_threshold_details.csv")
    print("Файл eval_threshold_details.csv содержит подробные метрики по каждому фото и confidence-порогу.")

if os.path.exists("recipe_eval_results.csv"):
    files.download("recipe_eval_results.csv")
    print("Файл recipe_eval_results.csv содержит метрики использования ингредиентов в рецепте.")



